### ISSUE TITLE
It appears the ingest on 3.6.8 python still has a problem (pyproj)

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#236]
We are seeing a bug in the current ingest processing...
ERROR:root:GribModelBuilderV01 handle_named_function: handle_wind_speed params ['*10 metre U wind component', '*10 metre V wind component']: Exception instantiating builder:
Traceback (most recent call last):
  File "/home/amb-verif/VxIngest/grib2_to_cb/grib_builder.py", line 272, in handle_named_function
    replace_with = getattr(self, func)(dict_params)
  File "/home/amb-verif/VxIngest/grib2_to_cb/grib_builder.py", line 741, in handle_wind_speed
    x_gridpoint = station["geo"][geo_index]["x_gridpoint"]
KeyError: 'x_gridpoint'
WARNING:root:GribModelBuilderV01 Builder.handle_data - value is (None,None)
ERROR:root:GribModelBuilderV01 handle_data: Exception instantiating builder
Traceback (most recent call last):
  File "/home/amb-verif/VxIngest/grib2_to_cb/grib_builder.py", line 321, in handle_data
    self.load_data(doc, data_key, data_elem)
  File "/home/amb-verif/VxIngest/grib2_to_cb/grib_builder.py", line 552, in load_data
    elem[key] = element[key][i]
TypeError: 'NoneType' object is not subscriptable

**Comment by randytpierce** [comment]
These problems are related to running a downlevel OS on adb-cb1. We have decided to run the ingest in containers so closing this issue.
